server:
  port: 8092

spring:
  application:
    name: MY_CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andra-Elena/ConfigurationRepo.git
          timeout: 10
          clone-on-start: true

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}